---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[as-asset::create]
#    attributes:
#      php:
#        version: '5.4'
#        date.timezone: 'Asia/Tokyo'
#        xdebug:
#          remote_enable: true
#        symfony2:
#          path: '/var/app'
